### ISSUE TITLE
enhavo:install order and wording

### ISSUE THREAD

**Issue by mkellermann** [enhavo/enhavo#129]
Admin username:
Admin email:
Admin password:
Are this information correct [yes]?

I think it is more usual to ask for password right after the username.
And in my opinion it is "Are these information correct"

offtopic: maybe we should think about putting username = email. and in the users profile he can set a displayname (if the author of news is displayed to visitors for example).

**Comment by FabianLiebl** [comment]
Added and merged, can be closed
