### ISSUE TITLE
Tidy up Button-bar

### ISSUE THREAD

**Issue by mkellermann** [enhavo/enhavo#137]
Take a look at the user edit form for example.

We see "Cancel","Save","Delete" in that order.
A user always has to read the button names so he chooses the right button.

At first the order should be changed. "Save" is the most used and primary button in this form. So the first step would be to group "cancel" and "delete" together visually. Second step would be to use a different style/color for the primary button generally (in all types of forms).

There are two approaches to order the buttons.
I think we could put the primary button wether to the most left or most right position of the button bar.

As "cancel" and not "delete" in this case is the secondary option, "cancel" should be placed next to "save" and "delete" next to "cancel".

The user shall not have to think about which button he has to click on. He should visually be transported to the right spot to look and click at without hessitating. He shall not think about "oh what are the other buttons do? am i right here?"

**Comment by gseidel** [comment]
`Save`, `Cancel` and `Delete` are now on different places with #611
