### ISSUE TITLE
Store XSS

### ISSUE THREAD

**Issue by wind226** [enhavo/enhavo#1543]
For background articles, fill in the title of the modified content:  `'"><iMg SrC=x OnErRoR=alert(9999)>{{7*7}}`

![image](https://user-images.githubusercontent.com/24953996/166136839-f939458f-9d83-4fbb-a808-f669f98cacbc.png)

View Article trigger XSS
https://demo.enhavo.com/article/cats
![image](https://user-images.githubusercontent.com/24953996/166136895-c6126fca-5431-4050-b247-2a2f02418607.png)

**Comment by gseidel** [comment]
Thanks @wind226 for open this issue. 

It was solved with PR #1550. The demo under https://demo.enhavo.com is provided by the project [enhavo/enhavo-demo](https://github.com/enhavo/enhavo-demo). We have to upgrade the demo to a newer enhavo version now. We keep that issue open until we fix it finally in the demo.

**Comment by gseidel** [comment]
The enhavo demo is up to date and the issue is solved now
