### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [enhavo/enhavo#1546]
Hey there!

I belong to an open source security research community, and a member (@wind226) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by gseidel** [comment]
Thanks @JamieSlome. We will provide a fix to close this issue and provide a SECURITY.md for further security concerns in future.

**Comment by JamieSlome** [comment]
@gseidel - great, appreciate your diligence! 👍 

Just for reference, the report can be found directly [here](https://huntr.dev/bounties/3ec65065-92ad-4759-a110-e77c9f180f97/), but we will send further details to the e-mail address you have elected in your `SECURITY.md`.

Let me know if you have any questions!
