### ISSUE TITLE
URGENT: Enhavo Grid WYSIWYG Bug after more than two textareas

### ISSUE THREAD

**Issue by mkellermann** [enhavo/enhavo#160]
Reproducable: Create a Page, add more than two wysiwyg-types (i chose three text-types in the example attached), save, open it again -> one is broken. i added six in total then two were broken.

![unbenannt-1](https://cloud.githubusercontent.com/assets/12298585/16084726/169dd0aa-331a-11e6-8a81-5df33869f915.jpg)

**Comment by FabianLiebl** [comment]
Unable to reproduce bug.
Tried branches master and 0.1, dev and prod environments, firefox/chrome on linux and firefox/chrome/ie on win 7 (virtual machine). Worked fine every time.

**Comment by FabianLiebl** [comment]
Added possible fix by ensuring uniqueness of textarea id
