### ISSUE TITLE
enhavo_list js sorting and add new item bug

### ISSUE THREAD

**Issue by gseidel** [enhavo/enhavo#169]
When i open a edit overview with a nested enhavo_list, the the following bugs appears:

* I create a new Item and can't add a subitem
* I have a list of sub items, if i move one up/down it moves up/down two times

**Comment by gseidel** [comment]
@FabianLiebl these commits are already merged to master, i think we can close that as well?

**Comment by FabianLiebl** [comment]
@gseidel Yes, can be closed
