### ISSUE TITLE
[EnhavoArticleBundle]Form building doesn't work in debug true

### ISSUE THREAD

**Issue by FabianLiebl** [enhavo/enhavo#39]
If debug = true in parameters.yml, building the backend form for articles will return a 500 error page: "Notice: Undefined index: label.yes" (delivered as Ajax answer).

Traced the error to Symfony FormBuilder trying to create choices for Article field 'social_media'.

**Comment by gseidel** [comment]
It looks like a Symfony2 bug. Here is the issue https://github.com/symfony/symfony/issues/17270. I think i they resolved that, this bug may also be solved. But for now we can use the workaround in #70d329a
