### ISSUE TITLE
[BlockBundle] Garbage collect for deleted grid items

### ISSUE THREAD

**Issue by FabianLiebl** [enhavo/enhavo#399]
Currently, grid items removed from their parent container remain in the database. They should be garbage collected or otherwise deleted.

**Comment by gseidel** [comment]
Please provide a console command, like `enhavo:media:clean-up`

`enhavo:block:clean-up`

**Comment by gseidel** [comment]
@FabianLiebl This command already exists. Do we still need to do anything here?
