### ISSUE TITLE
[EnhavoMediaBundle] Mimetype guesser strategy

### ISSUE THREAD

**Issue by FabianLiebl** [enhavo/enhavo#44]
The FileService->addFile() function determines the files mime type by file extension. This could be solved in a symfony strategy-way allowing determination by file content or users hooking in their own strategy providers.

**Comment by gseidel** [comment]
@FabianLiebl i think there is already some Symfony functionality like http://api.symfony.com/2.7/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeGuesser.html

Can we close that ticket?

**Comment by FabianLiebl** [comment]
Oh yes, I actually used it already. I forgot I opened this ticket. Ticket outdated, closed.
