### ISSUE TITLE
Login popup

### ISSUE THREAD

**Issue by FabianLiebl** [enhavo/enhavo#80]
At the moment, whenever the user gets a session timeout, the next request will return a login screen. This next request can be a form post or an ajax request, resulting in lost form data or failed ajax without a proper message for the user.

There should be a login popup and a saving/resending mechanism for form data for these cases.

**Comment by gseidel** [comment]
This has been fixed now. A popup will appear now if the user is logged out e.g. while he is saving. The data will not get lost, but the use still need to save again
