### ISSUE TITLE
Use PrependExtensionInterface instead of import configuration files

### ISSUE THREAD

**Issue by gseidel** [enhavo/enhavo#893]
At the moment we include the configurations file over yaml configuration files in ``config/packages/``.

The files look like:
```
imports:
    - { resource: '@EnhavoAppBundle/Resources/config/app/config.yml' }
```

But in the symfony docs, they advise to use ``PrependExtensionInterface``
https://symfony.com/doc/current/bundles/prepend_extension.html

It would be nice, if we can just keep our ``Resources/config/app/config.yaml``. So we just read the content and pass it to extension config.

```
    public function prepend(ContainerBuilder $container)
    {
        $configs = Yaml::parse(file_get_contents(__DIR__.'/../Resources/config/app/config.yaml'));
        foreach($configs as $name => $config) {
            $container->prependExtensionConfig($name, $config);
        }
    }
```

We need to apply that on all bundles

**Comment by indivisualvj** [comment]
@gseidel for bundles with more than one config file, does it make sense to list files with scandir first? does the order of including those multiple yaml files matter in any case?

**Comment by indivisualvj** [comment]
https://github.com/indivisualvj/enhavo/commit/b90418fdf670e815e9c51fa903e888c845644f66

**Comment by gseidel** [comment]
@indivisualvj A dynamic include is not necessary. The other config file should not be included generally. Just use the "old" way for this files, because the user in the project should decide if he want to include this file

**Comment by gseidel** [comment]
Done by #907
