### ISSUE TITLE
Yml to Yaml

### ISSUE THREAD

**Issue by gseidel** [enhavo/enhavo#894]
Wherever it possible, we should rename files with extension ``*.yml`` to ``*.yaml``. Because that is the new symfony convention

**Comment by gseidel** [comment]
For Doctrine Metafiles we could keep ``yml`` because ``yaml`` is not possible here. In future we will also move to xml for Metafiles

**Comment by indivisualvj** [comment]
@gseidel https://github.com/indivisualvj/enhavo/tree/yml2yaml

**Comment by gseidel** [comment]
@indivisualvj Just open a PR with status draft (https://github.blog/2019-02-14-introducing-draft-pull-requests/)

**Comment by gseidel** [comment]
Done by PR #907
