### ISSUE TITLE
[ShopBundle] Menus Order, Voucher, Product->Update are not working

### ISSUE THREAD

**Issue by indivisualvj** [enhavo/enhavo#903]
Steps to reproduce:
1. Install Enhavo
2. Enable Shop in enhavo.yaml
3. Click on the mentioned menu entries

Order -> Call to a member function isPaginated() on null
Voucher -> No type was given to create "Enhavo\Bundle\AppBundle\Column\Column"
Product -> Try to open Product -> Class does not exist

**Comment by gseidel** [comment]
Since version 0.7 the ShopBundle is not supported anymore. We have to completely refactor the ShopBundle
